import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  headingBox: {
    padding: 5,
    paddingBottom: 0,
    flexDirection: 'row',
    marginBottom: 25,
  },
  backButton: {
    position: 'absolute',
    zIndex: 50,
    borderRadius: 50,
    padding: 3,
    marginTop: 8,
    marginLeft: 8,
  },
  heading: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#0c4a6e',
    padding: 7,
    fontSize: 20,
    lineHeight: 22,
    marginLeft: '40%',
    marginBottom: 10,
  },
  promoBox: {
    flexDirection: 'row',
    paddingVertical: 3,
    paddingLeft: 0,
    paddingRight: 15,
    marginLeft: 10,
    backgroundColor: '#134e4a',
    height: '50%',
    width: '95%',
    borderRadius: 5,
  },
  commissionText: {
    fontSize: 18,
    lineHeight: 24,
    paddingLeft: 0,
    color: '#fff',
    marginLeft: 20,
    marginTop: 15,
    textAlign: 'left',
  },
  refferalCode: {
    marginTop: 28,
    marginLeft: 20,
    color: '#fff',
  },
  inputContainer: {
    flexDirection: 'row',
    alignItems: 'center',
    paddding: 5,
    paddingTop: 1,
    paddingLeft: 0,
  },
  forminput: {
    borderColor: '#EBEBEB',
    borderRightColor: '#004D40',
    borderTopColor: '#004D40',
    borderLeftColor: '#004D40',
    color: 'white',
    borderWidth: 1,
    borderRadius: 5,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
    minWidth: 200,
    height: 50,
    margin: 20,
    marginTop: 1,
  },
  linkButton: {
    backgroundColor: '#6b7280',
    borderRadius: 5,
    paddingHorizontal: 18,
    paddingVertical: 10,
  },
  linkText: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
  },
  rewardsContainer: {
    paddingLeft: 10,
    marginTop: -150,
  },
  rewardsBox: {
    paddingVertical: 5,
    paddingRight: 15,
    paddingLeft: 0,
    backgroundColor: '#fff',
    borderColor: '#d1d5db',
    borderWidth: 1,
    height: '50%',
    width: '97%',
    borderRadius: 5,
  },
  rewardsPanelText: {
    fontWeight: '500',
    paddingLeft: 0,
    marginLeft: 10,
    marginTop: 8,
    textAlign: 'left',
    fontSize: 18,
  },
  rewardsSubText: {
    paddingLeft: 0,
    marginLeft: 10,
    marginTop: 5,
    textAlign: 'left',
    color: '#9ca3af',
  },
  learnMoreText: {
    color: '#fb923c',
  },
});

export default styles;
