import {StyleSheet} from 'react-native';

const styles = StyleSheet.create({
  headingBox: {
    padding: 5,
    paddingBottom: 0,
    flexDirection: 'row',
    marginBottom: 25,
  },
  backButton: {
    position: 'absolute',
    zIndex: 50,
    borderRadius: 50,
    padding: 3,
    marginTop: 8,
    marginLeft: 8,
  },
  heading: {
    textAlign: 'center',
    fontWeight: 'bold',
    color: '#0c4a6e',
    padding: 7,
    fontSize: 20,
    lineHeight: 22,
    marginLeft: '5%',
    marginBottom: 10,
  },
  subtitles: {
    paddingLeft: 0,
    marginLeft: 5,
    textAlign: 'center',
    marginLeft: 30,
    color: '#9ca3af',
    fontSize: 13,
  },
  searchBox: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 10,
    paddingTop: 5,
    paddingLeft: 0,
  },
  searchInput: {
    borderColor: '#555B6A',
    borderRightColor: '#F2F2F2',
    borderTopColor: '#F2F2F2',
    borderLeftColor: '#F2F2F2',
    color: '#555B6A',
    borderWidth: 1,
    borderRadius: 0,
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 0,
    width: 300,
    height: 50,
    margin: 20,
    marginTop: 1,
  },
  searchButton: {
    paddingVertical: 10,
  },
  messageBox: {
    paddingVertical: 10,
    paddingRight: 2,
    paddingLeft: 0,
    backgroundColor: '#0c4a6e',
    height: '52.5%',
    width: '98%',
    borderRadius: 5,
  },
  imageStyle: {
    padding: 4,
    marginLeft: 20,
    marginTop: 5,
    height: 50,
    width: 50,
  },
  messageText: {
    paddingLeft: 0,
    marginLeft: 10,
    marginTop: 10,
    marginBottom: 2,
    fontWeight: '700',
    textAlign: 'center',
    color: '#f3f4f6',
    fontSize: 20,
  },
  messageSubText: {
    paddingLeft: 0,
    marginLeft: 10,
    textAlign: 'center',
    color: '#d1d5db',
    fontSize: 16,
    marginBottom: 5,
  },
  messageButton: {
    marginTop: 5,
    backgroundColor: '#15803d',
    width: '45%',
    borderRadius: 5,
    paddingVertical: 12,
    justifyContent: 'space-evenly',
    marginLeft: 15,
    paddingHorizontal: 5,
  },
  messageButtonText: {
    color: '#fff',
    fontSize: 18,
    textAlign: 'center',
  },
  articleHeading: {
    fontWeight: '600',
    marginLeft: 5,
    color: '#111827',
    padding: 10,
    paddingLeft: 5,
    paddingBottom: 5,
    textAlign: 'left',
    fontSize: 20,
  },
  articleListItem: {
    flexDirection: 'row',
    alignItems: 'center',
    padding: 5,
    paddingVertical: 20,
    // paddingLeft: 5,
    marginLeft: 2,
  },
  articleItem: {
    marginLeft: 5,
    fontWeight: '300',
    fontSize: 18,
    marginLeft: 5,
  },
});

export default styles;
